### ISSUE TITLE
Magisk module possibility

### ISSUE THREAD

**Issue by anasfanani** [pacman-for-android/pacman-for-android#1]
Do you think is it possible to use pacman for android with the power of magisk module ?

**Comment by kxxt** [comment]
Yes, it is possible. But there will be some bugs because by default Android kernel doesn't support some linux-ish things like SYSVIPC.

termux emulates SYSVIPC and possibly other missing parts, which I won't do in pacman-for-android. A custom kernel is needed for everything to work.

And FYI, this project is still an experiment which is not ready for production. Thanks for your interest in this project.

**Comment by anasfanani** [comment]
But.. if it depends on a custom kernel, some people may not be able to use pacman for android, in my opinion it should provide pacman with limited functions if not using custom kernel, if it requires more advanced features, users need to create a custom kernel.

FYI, I came here from your [blog posts](https://www.kxxt.dev/blog/clash-for-android-and-tailscale/), since I develop a [magisk tailscaled](https://github.com/anasfanani/Magisk-Tailscaled) module for magisk.

**Comment by kxxt** [comment]
> But.. if it depends on a custom kernel, some people may not be able to use pacman for android, in my opinion it should provide pacman with limited functions if not using custom kernel, if it requires more advanced features, users need to create a custom kernel.

Yes, I didn't plan to support a large audience. Probably I will only support building and integrating it in an AOSP tree because I usually want to do modifications to a system in source form, not in binary form. If you only need pacman, termux-pacman might be more suitable: https://github.com/termux-pacman

Basic functionality should work with any android superuser solution, but some bugs are expected: e g. docker, python multithreading will not work.

Some repos about integrating it into LineageOS:

- https://github.com/android-kxxt/android_vendor_pfa
- https://github.com/android-kxxt/android_device_xiaomi_sm8450-common
- https://github.com/android-kxxt/android_system_sepolicy
- kernel, QCOM GKI: https://github.com/android-kxxt/android_kernel_platform_msm-kernel and https://github.com/android-kxxt/clo_kernel_common
- kernel, building in lineage OS way: https://github.com/android-kxxt/android_kernel_xiaomi_sm8250/commits/lineage-20-pfa/

I enabled kernelsu in the above kernel repos, but it's just my personal preference, not a requirement for PFA. sudo provided by PFA will work, nonetheless not accessible by android apps.

**Comment by anasfanani** [comment]
> Yes, I didn't plan to support a large audience. Probably I will only support building and integrating it in an AOSP tree because I usually want to do modifications to a system in source form.

Hmm, I see, you are targeting a higher level of system modification, I don't have enough knowledge for that.

> If you only need pacman, termux-pacman might be more suitable: https://github.com/termux-pacman
>
> Basic functionality should work with any android superuser solution, but some bugs are expected: e g. docker, python multithreading will not work.

Thank you for the explanation of termux-pacman, maybe for now termux-pacman is enough for me.

> Some repos about integrating it into LineageOS:
> 
> https://github.com/android-kxxt/android_vendor_pfa
> https://github.com/android-kxxt/android_device_xiaomi_sm8450-common
> https://github.com/android-kxxt/android_system_sepolicy
> kernel, QCOM GKI: https://github.com/android-kxxt/android_kernel_platform_msm-kernel and https://github.com/android-kxxt/clo_kernel_common
> kernel, building in lineage OS way: https://github.com/android-kxxt/android_kernel_xiaomi_sm8250/commits/lineage-20-pfa/
> I enabled kernelsu in the above kernel repos, but it's just my personal preference, not a requirement for PFA. sudo provided by PFA will work, nonetheless not accessible by android apps.

Thanks for referencing this, currently I need to learn more about custom kernels, sorry I can't reply much.

Anyway thank you very much for the discussion, I will close this issue since you gave me the solution about termux-pacman.
